//go:build !ignore_autogenerated

/*
Copyright 2025 The Upbound Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigPatchSecretRef) DeepCopyInto(out *ConfigPatchSecretRef) {
	*out = *in
	out.LocalSecretReference = in.LocalSecretReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigPatchSecretRef.
func (in *ConfigPatchSecretRef) DeepCopy() *ConfigPatchSecretRef {
	if in == nil {
		return nil
	}
	out := new(ConfigPatchSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pipeline) DeepCopyInto(out *Pipeline) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Traces != nil {
		in, out := &in.Traces, &out.Traces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pipeline.
func (in *Pipeline) DeepCopy() *Pipeline {
	if in == nil {
		return nil
	}
	out := new(Pipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedTelemetryConfig) DeepCopyInto(out *SharedTelemetryConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedTelemetryConfig.
func (in *SharedTelemetryConfig) DeepCopy() *SharedTelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(SharedTelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedTelemetryConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedTelemetryConfigList) DeepCopyInto(out *SharedTelemetryConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SharedTelemetryConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedTelemetryConfigList.
func (in *SharedTelemetryConfigList) DeepCopy() *SharedTelemetryConfigList {
	if in == nil {
		return nil
	}
	out := new(SharedTelemetryConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedTelemetryConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedTelemetryConfigProvisioningFailure) DeepCopyInto(out *SharedTelemetryConfigProvisioningFailure) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedTelemetryConfigProvisioningFailure.
func (in *SharedTelemetryConfigProvisioningFailure) DeepCopy() *SharedTelemetryConfigProvisioningFailure {
	if in == nil {
		return nil
	}
	out := new(SharedTelemetryConfigProvisioningFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedTelemetryConfigSpec) DeepCopyInto(out *SharedTelemetryConfigSpec) {
	*out = *in
	in.ControlPlaneSelector.DeepCopyInto(&out.ControlPlaneSelector)
	in.Exporters.DeepCopyInto(&out.Exporters)
	in.ExportPipeline.DeepCopyInto(&out.ExportPipeline)
	if in.ConfigPatchSecretRefs != nil {
		in, out := &in.ConfigPatchSecretRefs, &out.ConfigPatchSecretRefs
		*out = make([]ConfigPatchSecretRef, len(*in))
		copy(*out, *in)
	}
	if in.Processors != nil {
		in, out := &in.Processors, &out.Processors
		*out = (*in).DeepCopy()
	}
	in.ProcessorPipeline.DeepCopyInto(&out.ProcessorPipeline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedTelemetryConfigSpec.
func (in *SharedTelemetryConfigSpec) DeepCopy() *SharedTelemetryConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SharedTelemetryConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedTelemetryConfigStatus) DeepCopyInto(out *SharedTelemetryConfigStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	if in.SelectedControlPlanes != nil {
		in, out := &in.SelectedControlPlanes, &out.SelectedControlPlanes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([]SharedTelemetryConfigProvisioningFailure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedTelemetryConfigStatus.
func (in *SharedTelemetryConfigStatus) DeepCopy() *SharedTelemetryConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SharedTelemetryConfigStatus)
	in.DeepCopyInto(out)
	return out
}
