//go:build !ignore_autogenerated

/*
Copyright 2025 The Upbound Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	spacesv1alpha1 "github.com/upbound/up-sdk-go/apis/spaces/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicyStatusCondition) DeepCopyInto(out *ClusterPolicyStatusCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicyStatusCondition.
func (in *ClusterPolicyStatusCondition) DeepCopy() *ClusterPolicyStatusCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicyStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedUpboundPolicy) DeepCopyInto(out *SharedUpboundPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedUpboundPolicy.
func (in *SharedUpboundPolicy) DeepCopy() *SharedUpboundPolicy {
	if in == nil {
		return nil
	}
	out := new(SharedUpboundPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedUpboundPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedUpboundPolicyList) DeepCopyInto(out *SharedUpboundPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SharedUpboundPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedUpboundPolicyList.
func (in *SharedUpboundPolicyList) DeepCopy() *SharedUpboundPolicyList {
	if in == nil {
		return nil
	}
	out := new(SharedUpboundPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedUpboundPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedUpboundPolicyProvisioningFailure) DeepCopyInto(out *SharedUpboundPolicyProvisioningFailure) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedUpboundPolicyProvisioningFailure.
func (in *SharedUpboundPolicyProvisioningFailure) DeepCopy() *SharedUpboundPolicyProvisioningFailure {
	if in == nil {
		return nil
	}
	out := new(SharedUpboundPolicyProvisioningFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedUpboundPolicyProvisioningSuccess) DeepCopyInto(out *SharedUpboundPolicyProvisioningSuccess) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedUpboundPolicyProvisioningSuccess.
func (in *SharedUpboundPolicyProvisioningSuccess) DeepCopy() *SharedUpboundPolicyProvisioningSuccess {
	if in == nil {
		return nil
	}
	out := new(SharedUpboundPolicyProvisioningSuccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedUpboundPolicySpec) DeepCopyInto(out *SharedUpboundPolicySpec) {
	*out = *in
	if in.PolicyMetadata != nil {
		in, out := &in.PolicyMetadata, &out.PolicyMetadata
		*out = new(spacesv1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	in.ControlPlaneSelector.DeepCopyInto(&out.ControlPlaneSelector)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedUpboundPolicySpec.
func (in *SharedUpboundPolicySpec) DeepCopy() *SharedUpboundPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SharedUpboundPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedUpboundPolicyStatus) DeepCopyInto(out *SharedUpboundPolicyStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([]SharedUpboundPolicyProvisioningFailure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = make([]SharedUpboundPolicyProvisioningSuccess, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedUpboundPolicyStatus.
func (in *SharedUpboundPolicyStatus) DeepCopy() *SharedUpboundPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SharedUpboundPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
