//go:build !ignore_autogenerated

/*
Copyright 2025 The Upbound Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	spacesv1alpha1 "github.com/upbound/up-sdk-go/apis/spaces/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneStatus) DeepCopyInto(out *CrossplaneStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneStatus.
func (in *CrossplaneStatus) DeepCopy() *CrossplaneStatus {
	if in == nil {
		return nil
	}
	out := new(CrossplaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericSpaceBackupResourceSelector) DeepCopyInto(out *GenericSpaceBackupResourceSelector) {
	*out = *in
	in.ResourceSelector.DeepCopyInto(&out.ResourceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericSpaceBackupResourceSelector.
func (in *GenericSpaceBackupResourceSelector) DeepCopy() *GenericSpaceBackupResourceSelector {
	if in == nil {
		return nil
	}
	out := new(GenericSpaceBackupResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstalledComponentsStatus) DeepCopyInto(out *InstalledComponentsStatus) {
	*out = *in
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(CrossplaneStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstalledComponentsStatus.
func (in *InstalledComponentsStatus) DeepCopy() *InstalledComponentsStatus {
	if in == nil {
		return nil
	}
	out := new(InstalledComponentsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackup) DeepCopyInto(out *SpaceBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackup.
func (in *SpaceBackup) DeepCopy() *SpaceBackup {
	if in == nil {
		return nil
	}
	out := new(SpaceBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupConfig) DeepCopyInto(out *SpaceBackupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupConfig.
func (in *SpaceBackupConfig) DeepCopy() *SpaceBackupConfig {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceBackupConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupConfigList) DeepCopyInto(out *SpaceBackupConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpaceBackupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupConfigList.
func (in *SpaceBackupConfigList) DeepCopy() *SpaceBackupConfigList {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceBackupConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupConfigSpec) DeepCopyInto(out *SpaceBackupConfigSpec) {
	*out = *in
	in.ObjectStorage.DeepCopyInto(&out.ObjectStorage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupConfigSpec.
func (in *SpaceBackupConfigSpec) DeepCopy() *SpaceBackupConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupControlPlanesStatus) DeepCopyInto(out *SpaceBackupControlPlanesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupControlPlanesStatus.
func (in *SpaceBackupControlPlanesStatus) DeepCopy() *SpaceBackupControlPlanesStatus {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupControlPlanesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupCredentials) DeepCopyInto(out *SpaceBackupCredentials) {
	*out = *in
	in.CommonCredentialSelectors.DeepCopyInto(&out.CommonCredentialSelectors)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupCredentials.
func (in *SpaceBackupCredentials) DeepCopy() *SpaceBackupCredentials {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupDefinition) DeepCopyInto(out *SpaceBackupDefinition) {
	*out = *in
	in.ConfigRef.DeepCopyInto(&out.ConfigRef)
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(SpaceBackupResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(SpaceBackupResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlaneBackups != nil {
		in, out := &in.ControlPlaneBackups, &out.ControlPlaneBackups
		*out = new(spacesv1alpha1.ControlPlaneBackupConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Failures.DeepCopyInto(&out.Failures)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupDefinition.
func (in *SpaceBackupDefinition) DeepCopy() *SpaceBackupDefinition {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupFailuresConfig) DeepCopyInto(out *SpaceBackupFailuresConfig) {
	*out = *in
	if in.ControlPlanes != nil {
		in, out := &in.ControlPlanes, &out.ControlPlanes
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupFailuresConfig.
func (in *SpaceBackupFailuresConfig) DeepCopy() *SpaceBackupFailuresConfig {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupFailuresConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupList) DeepCopyInto(out *SpaceBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpaceBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupList.
func (in *SpaceBackupList) DeepCopy() *SpaceBackupList {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupObjectStorage) DeepCopyInto(out *SpaceBackupObjectStorage) {
	*out = *in
	in.BackupObjectStorage.DeepCopyInto(&out.BackupObjectStorage)
	in.Credentials.DeepCopyInto(&out.Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupObjectStorage.
func (in *SpaceBackupObjectStorage) DeepCopy() *SpaceBackupObjectStorage {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupObjectStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupResourceSelector) DeepCopyInto(out *SpaceBackupResourceSelector) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = new(spacesv1alpha1.ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlanes != nil {
		in, out := &in.ControlPlanes, &out.ControlPlanes
		*out = new(spacesv1alpha1.ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(spacesv1alpha1.ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Extras != nil {
		in, out := &in.Extras, &out.Extras
		*out = make([]GenericSpaceBackupResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupResourceSelector.
func (in *SpaceBackupResourceSelector) DeepCopy() *SpaceBackupResourceSelector {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupSchedule) DeepCopyInto(out *SpaceBackupSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupSchedule.
func (in *SpaceBackupSchedule) DeepCopy() *SpaceBackupSchedule {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceBackupSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupScheduleDefinition) DeepCopyInto(out *SpaceBackupScheduleDefinition) {
	*out = *in
	in.SpaceBackupDefinition.DeepCopyInto(&out.SpaceBackupDefinition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupScheduleDefinition.
func (in *SpaceBackupScheduleDefinition) DeepCopy() *SpaceBackupScheduleDefinition {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupScheduleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupScheduleList) DeepCopyInto(out *SpaceBackupScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpaceBackupSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupScheduleList.
func (in *SpaceBackupScheduleList) DeepCopy() *SpaceBackupScheduleList {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceBackupScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupScheduleSpec) DeepCopyInto(out *SpaceBackupScheduleSpec) {
	*out = *in
	in.SpaceBackupScheduleDefinition.DeepCopyInto(&out.SpaceBackupScheduleDefinition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupScheduleSpec.
func (in *SpaceBackupScheduleSpec) DeepCopy() *SpaceBackupScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupScheduleStatus) DeepCopyInto(out *SpaceBackupScheduleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	if in.LastBackup != nil {
		in, out := &in.LastBackup, &out.LastBackup
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupScheduleStatus.
func (in *SpaceBackupScheduleStatus) DeepCopy() *SpaceBackupScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupSpec) DeepCopyInto(out *SpaceBackupSpec) {
	*out = *in
	in.SpaceBackupDefinition.DeepCopyInto(&out.SpaceBackupDefinition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupSpec.
func (in *SpaceBackupSpec) DeepCopy() *SpaceBackupSpec {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceBackupStatus) DeepCopyInto(out *SpaceBackupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.ControlPlanes = in.ControlPlanes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceBackupStatus.
func (in *SpaceBackupStatus) DeepCopy() *SpaceBackupStatus {
	if in == nil {
		return nil
	}
	out := new(SpaceBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceLicense) DeepCopyInto(out *SpaceLicense) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceLicense.
func (in *SpaceLicense) DeepCopy() *SpaceLicense {
	if in == nil {
		return nil
	}
	out := new(SpaceLicense)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceLicense) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceLicenseCapacity) DeepCopyInto(out *SpaceLicenseCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceLicenseCapacity.
func (in *SpaceLicenseCapacity) DeepCopy() *SpaceLicenseCapacity {
	if in == nil {
		return nil
	}
	out := new(SpaceLicenseCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceLicenseList) DeepCopyInto(out *SpaceLicenseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpaceLicense, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceLicenseList.
func (in *SpaceLicenseList) DeepCopy() *SpaceLicenseList {
	if in == nil {
		return nil
	}
	out := new(SpaceLicenseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceLicenseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceLicenseRestrictions) DeepCopyInto(out *SpaceLicenseRestrictions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceLicenseRestrictions.
func (in *SpaceLicenseRestrictions) DeepCopy() *SpaceLicenseRestrictions {
	if in == nil {
		return nil
	}
	out := new(SpaceLicenseRestrictions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceLicenseSecretRef) DeepCopyInto(out *SpaceLicenseSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceLicenseSecretRef.
func (in *SpaceLicenseSecretRef) DeepCopy() *SpaceLicenseSecretRef {
	if in == nil {
		return nil
	}
	out := new(SpaceLicenseSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceLicenseSpec) DeepCopyInto(out *SpaceLicenseSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SpaceLicenseSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceLicenseSpec.
func (in *SpaceLicenseSpec) DeepCopy() *SpaceLicenseSpec {
	if in == nil {
		return nil
	}
	out := new(SpaceLicenseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceLicenseStatus) DeepCopyInto(out *SpaceLicenseStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(SpaceLicenseCapacity)
		**out = **in
	}
	if in.EnabledFeatures != nil {
		in, out := &in.EnabledFeatures, &out.EnabledFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.GracePeriodEndsAt != nil {
		in, out := &in.GracePeriodEndsAt, &out.GracePeriodEndsAt
		*out = (*in).DeepCopy()
	}
	if in.Restrictions != nil {
		in, out := &in.Restrictions, &out.Restrictions
		*out = new(SpaceLicenseRestrictions)
		**out = **in
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(SpaceLicenseUsage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceLicenseStatus.
func (in *SpaceLicenseStatus) DeepCopy() *SpaceLicenseStatus {
	if in == nil {
		return nil
	}
	out := new(SpaceLicenseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceLicenseUsage) DeepCopyInto(out *SpaceLicenseUsage) {
	*out = *in
	if in.FirstMeasurement != nil {
		in, out := &in.FirstMeasurement, &out.FirstMeasurement
		*out = (*in).DeepCopy()
	}
	if in.LastMeasurement != nil {
		in, out := &in.LastMeasurement, &out.LastMeasurement
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceLicenseUsage.
func (in *SpaceLicenseUsage) DeepCopy() *SpaceLicenseUsage {
	if in == nil {
		return nil
	}
	out := new(SpaceLicenseUsage)
	in.DeepCopyInto(out)
	return out
}
